version: '2.4'

networks:
  default:
    name: neo_go_network
    ipam:
      config:
        - subnet: 172.200.0.0/24
          gateway: 172.200.0.254

services:
  node_one:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_one
    expose: [ "30333" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30333']
    volumes:
      - ./wallet.one.json:/config/wallet.json
      - ./go.protocol.privnet.one.7.yml:/config/protocol.privnet.yml

  node_two:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_two
    expose: [ "30334" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30334']
    volumes:
      - ./wallet.two.json:/config/wallet.json
      - ./go.protocol.privnet.two.7.yml:/config/protocol.privnet.yml

  node_three:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_three
    expose: [ "30335" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30335']
    volumes:
      - ./wallet.three.json:/config/wallet.json
      - ./go.protocol.privnet.three.7.yml:/config/protocol.privnet.yml

  node_four:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_four
    expose: [ "30336" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30336']
    volumes:
      - ./wallet.four.json:/config/wallet.json
      - ./go.protocol.privnet.four.7.yml:/config/protocol.privnet.yml

  node_five:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_five
    expose: [ "30337" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30337']
    volumes:
      - ./wallet.five.json:/config/wallet.json
      - ./go.protocol.privnet.five.7.yml:/config/protocol.privnet.yml

  node_six:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_six
    expose: [ "30338" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30338']
    volumes:
      - ./wallet.six.json:/config/wallet.json
      - ./go.protocol.privnet.six.7.yml:/config/protocol.privnet.yml

  node_seven:
    extends:
      service: base-go
      file: docker-compose.node.yml
    container_name: neo_go_node_seven
    expose: [ "30339" ]
    healthcheck:
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 30339']
    volumes:
      - ./wallet.seven.json:/config/wallet.json
      - ./go.protocol.privnet.seven.7.yml:/config/protocol.privnet.yml

  healthy:
    image: alpine
    depends_on:
      node_one:
        condition: service_healthy
      node_two:
        condition: service_healthy
      node_three:
        condition: service_healthy
      node_four:
        condition: service_healthy
      node_five:
        condition: service_healthy
      node_six:
        condition: service_healthy
      node_seven:
        condition: service_healthy
